Update Python version and add syntax check step
Updated Python version and added a pre-check for Python syntax in files.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,7 +13,7 @@ on:
   workflow_dispatch: {}
 
 env:
-  python: 3.14.0
+  python: 3.14.2
 
 jobs:
   build:
@@ -64,7 +64,7 @@ jobs:
             libasound2-dev \
             libpulse-dev
 
-      # UPX (skip macOS)
+      # UPX
       - name: Setup UPX
         if: matrix.os != 'macos-latest'
         uses: crazy-max/ghaction-upx@v3
@@ -152,6 +152,23 @@ jobs:
         if: false # disable for now
         run: python setup.py build_ext --inplace
 
+      - name: Pre-check python files
+        run: |
+          set -o pipefail
+          failed=0
+          find app -type f -name "*.py" | while IFS= read -r file; do
+              if uv run python -m py_compile "$file" &>/dev/null; then
+                  echo "OK: $file"
+              else
+                  echo "FAIL: $file"
+                  failed=1
+              fi
+          done
+          if [ "$failed" -ne 0 ]; then
+              echo "❌ Python syntax check failed"
+              exit 1
+          fi
+
       # Build PyNES
       - name: Build PyNES
         id: build
@@ -195,7 +212,7 @@ jobs:
             cp -r roms/* upload/ 2>/dev/null || true
           fi
           
-          cp LICENSE.md upload/ 2>/dev/null || true
+          cp LICENSE.md upload/LICENSE 2>/dev/null || true
 
       - name: Prepare Zip Name
         id: export_name
